### ISSUE TITLE
Update-Database error: Could not load file or assembly EnvDTE Version=17

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/ef6#1898] opened 2021-09-10 08:12 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Update-Database-error:-Could-not-load-fi/1523337)._

---
[regression] [worked-in:17.0.0 Preview 3.1]
Migration could not apply into database.
I tried both without parameters and with parameters - always an error
Update-Database in VS022 Preview3
! [s1.jpg] (https://aka.ms/dc/image?name=B1ed2108d367e448aa5b6917cc3052add637665935047098699_s1.jpg&tid=1ed2108d367e448aa5b6917cc3052add637665935047098699)

Update-Database in VS017
! [s2.jpg] (https://aka.ms/dc/image?name=Be0fdc5eaa27848caa8ca7bf732da4929637665935199828014_s2.jpg&tid=e0fdc5eaa27848caa8ca7bf732da4929637665935199828014)

Project: .Net Framework 4.8 Web App.

---
#### Feedback Bot on 9/7/2021, 10:43 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment] 2021-09-10 08:13
Duplicate of #1897

**Closed by ajcvickers** 2021-09-10 08:13 UTC
