### ISSUE TITLE
while running migration in vs 2022 . i am facing this issue. but in 2019 migration is running. please help

### ISSUE THREAD

**Issue by twostepdevelopers** [dotnet/ef6#1995] opened 2022-05-17 05:21 UTC
while running migration in vs 2022 . i am facing this issue. but in 2019 migration is running. please help 

![image](https://user-images.githubusercontent.com/35261297/168734873-c5210f82-b160-4dc7-82b3-a7398f0d3e43.png)

EF version:6
Database provider: sql server
Target framework: .net framewrok 4.5
Operating system: windows
IDE: vs2022

**Comment by MikeDPeterson** [comment] 2022-05-23 20:06
@twostepdevelopers see https://github.com/dotnet/ef6/issues/1881

**Comment by ajcvickers** [comment] 2022-05-25 13:28
Duplicate of #1916 and several other issues.

**Closed by ajcvickers** 2022-05-25 13:28 UTC
