### ISSUE TITLE
“无法解析依赖项。"EntityFramework 6.4.4"与'EntityFramework.zh-Hans6.2.0约束: EntityFramework (= 6.2.0)'不兼容。”

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/ef6#1990] opened 2022-05-02 15:59 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/“无法解析依赖项。EntityFramework-644与Entity/10027384)._

---
[severity:Other]
运行所选代码生成器时出错:
“无法解析依赖项。"EntityFramework 6.4.4"与'EntityF
![N)$]]YHD21MWOI_%ZD}N%42.png](https://aka.ms/dc/image?name=Ba5c669fec315454cb096b9bbb67a264e637868161050939827_N)$%5D%5DYHD21MWOI_%25ZD%7DN%2542.png&tid=a5c669fec315454cb096b9bbb67a264e637868161050939827)
ramework.zh-Hans6.2.0约束: EntityFramework (= 6.2.0)'不兼容。”

---
#### Feedback Bot on 5/2/2022, 03:26 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment] 2022-05-02 16:05
Duplicate of #1307

**Closed by ajcvickers** 2022-05-02 16:05 UTC
