### ISSUE TITLE
Microsoft.data.sqlclient Support for EF6

### ISSUE THREAD

**Issue by Hassan3152** [dotnet/ef6#1935] opened 2022-01-02 11:35 UTC
Is there any plan to support EF 6 in Microsoft.data.sqlclient as i can't authenticate with azure sql using authentication type "Active directory managed identity" with EF 6.

**Comment by roji** [comment] 2022-01-02 12:52
Duplicate of #823

**Closed** 2022-01-02 12:53 UTC
Labels: closed-duplicate
