### ISSUE TITLE
Support for Microsoft.Data.SqlClient

### ISSUE THREAD

**Issue by timomta** [dotnet/ef6#2038] opened 2022-10-03 20:43 UTC
Hello,
I'm trying to move an application to Azure PaaS and leverage AAD auth to SQL MI. The application is .Net 4.8 full framework and is using EF 6. We're hitting lack of support in System.Data.SqlClient for the AAD Authentication keyword(s) in the connection string. We need to use Microsoft.Data.SqlClient.
It is too much of a lift to convert the application to .Net Core and EF.
I see a lot of traffic over a few years in this issue on the topic: https://github.com/dotnet/ef6/issues/823
There is a call out here that support for it is part of the limited EF6 roadmap: https://github.com/dotnet/ef6/issues/1935
There is also some text in the roadmap that says it will be added "this year": https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/plan#theme-clear-path-forward-from-ef6
"we plan to make it clear on the legacy EF6 GitHub repo that we are not planning any future work on EF6. The exception to this is that we plan to add support for using EF6 with Microsoft.Data.SqlClient. This will be limited to runtime support. "

Has the mentioned planned support been added for Microsoft.Data.SqlClient in EF6?

**Comment by ErikEJ** [comment] 2022-10-03 21:00
Duplicate of #832 - and you can use my package today. Plan is to release official package this year.

**Closed** 2022-10-04 19:47 UTC
Labels: closed-duplicate
