### ISSUE TITLE
Looking for reference applications on Entity Framework

### ISSUE THREAD

**Issue by sdg002** [dotnet/ef6#1643] opened 2020-04-10 22:30 UTC
Hi All,
I am looking for a moderately complex sample application(s) built on EF which could be used as an example for an upcoming project.

Any suggestions?

Thank you.

**Comment by ajcvickers** [comment] 2020-04-13 22:04
Duplicate of https://github.com/dotnet/EntityFramework.Docs/issues/2269

**Closed by ajcvickers** 2020-04-13 22:04 UTC
