### ISSUE TITLE
VS 2022 Add-Migration throw System.ArgumentNullException

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/ef6#1937] opened 2022-01-06 18:29 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS-2022-Add-Migration-throw-SystemArgum/1581462)._

---
[regression] [worked-in:17.0]
My project is based on .Net 4.8, When using Add-Migration it throws System.ArgumentNullException

```
Add-Migration -Name NotificationInfoes_Add_AppType -ConfigurationTypeName WebApiHost.Migrations.Configuration
System.ArgumentNullException: 值不能为 null。
参数名: type
   在 System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   在 System.Activator.CreateInstance(Type type, Object[] args)
   在 System.Data.Entity.Migrations.Extensions.ProjectExtensions.GetProjectTypes(Project project, Int32 shellVersion)
   在 System.Data.Entity.Migrations.Extensions.ProjectExtensions.IsWebSiteProject(Project project)
   在 System.Data.Entity.Migrations.Extensions.ProjectExtensions.GetTargetDir(Project project)
   在 System.Data.Entity.Migrations.MigrationsDomainCommand.GetFacade(String configurationTypeName, Boolean useContextWorkingDirectory)
   在 System.Data.Entity.Migrations.AddMigrationCommand.Execute(String name, Boolean force, Boolean ignoreChanges)
   在 System.Data.Entity.Migrations.MigrationsDomainCommand.Execute(Action command)
```

---
#### Feedback Bot on 11/12/2021, 08:25 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment] 2022-01-06 18:33
Duplicate of #1916

**Closed by ajcvickers** 2022-01-06 18:33 UTC
